<template>
  <div>
    <h2>Privacy Statement</h2>
    <p><strong>Effective: February 7, 2019</strong></p>
    <p>Your privacy is very important to us. Please read below to see how Join It handles the information that we collect. Before you get to the details, here are a few of our fundamental privacy principles:</p>
    <p>The data you provide Join It will only be used by you. We do not reuse, share, or sell any data for marketing, aggregating, or analytical purposes. Your data is yours.</p>
    <p>Join It only stores and displays the data you provide for the purpose of making your membership management tool useful.</p>
    <p>Some information you upload to your public profile on Join It may be seen by others. This includes the public information that you provide about your organization, such as a description, contact email address, header and logo image, published events, available membership types, etc.</p>
    <p>We give you several ways to control the privacy of your personal information and are continuously working to enhance privacy options available to you.</p>
    <p>Join It respects your privacy and shares your concern about the security of information you may submit to Join It’s websites and the related mobile applications and services (collectively, the “Services”). Our privacy policy (the “Privacy Policy”) explains the information we collect, how we use and share it, how to manage your privacy settings and your rights in connection with the Services. Please also read the Terms of Service which sets out the terms governing the Services.</p>
    <p>Join It is headquartered in San Francisco and our Services are provided to you by Join It, Inc. If you are a resident of the European Union (“EU”), Join It, Inc. is the controller of your personal data for the purposes of EU data protection law.</p>
    <p>This policy was written in English. To the extent a translated version conflicts with the English version, the English version controls. Unless indicated otherwise, this Privacy Policy does not apply to third party products or services or the practices of companies that we do not own or control, including other companies you might interact with on or through the services Join It provides.</p>
    <h2>Privacy Policy</h2>
    <p>Join It, Inc. ("us", "we", or "our") operates the <a href="/">www.joinit.org</a> website (the "Service").</p>
    <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
    <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our <a href="/terms">Terms and Conditions</a>, accessible from <a href="/">www.joinit.org</a></p>
    <h3>Definitions</h3>
    <h4>Service</h4>
    <p>Service is the www.joinit.org website operated by Join It, Inc.</p>
    <h4>Personal Data</h4>
    <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
    <h4>Usage Data</h4>
    <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
    <h4>Cookies</h4>
    <p>Cookies are small pieces of data stored on your device (computer or mobile device).</p>
    <h4>Data Controller</h4>
    <p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
    <p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
    <h4>Data Processors (or Service Providers)</h4>
    <p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>
    <p>We may use the services of various Service Providers in order to process your data more effectively.</p>
    <h4>Data Subject (or User)</h4>
    <p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
    <h3>Information Collection And Use</h3>
    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
    <h4><em>Types of Data Collected</em></h4>
    <h4>Personal Data</h4>
    <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
    <ul>
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Phone number</li>
      <li>Address, State, Province, ZIP/Postal code, City</li>
      <li>Cookies and Usage Data</li>
    </ul>
    <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</p>
    <h4>Usage Data</h4>
    <p>We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
    <h4>Tracking and Cookies Data</h4>
    <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
    <p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
    <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
    <p>Examples of Cookies we use:</p>
    <ul>
      <li>Session Cookies. We use Session Cookies to operate our Service.</li>
      <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
      <li>Security Cookies. We use Security Cookies for security purposes.</li>
    </ul>
    <h4>Use of Data</h4>
    <p>Join It, Inc. uses the collected data for various purposes:</p>
    <ul>
      <li>To provide and maintain our Service</li>
      <li>To notify you about changes to our Service</li>
      <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
      <li>To provide customer support</li>
      <li>To gather analysis or valuable information so that we can improve our Service</li>
      <li>To monitor the usage of our Service</li>
      <li>To detect, prevent and address technical issues</li>
      <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
    </ul>
    <p>Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR) If you are from the European Economic Area (EEA), Join It, Inc. legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
    <p>Join It, Inc. may process your Personal Data because:</p>
    <ul>
      <li>We need to perform a contract with you</li>
      <li>You have given us permission to do so</li>
      <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
      <li>For payment processing purposes</li>
      <li>To comply with the law</li>
    </ul>
    <h4>Retention of Data</h4>
    <p>Join It, Inc. will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
    <p>Join It, Inc. will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
    <h4>Transfer Of Data</h4>
    <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
    <p>If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>
    <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
    <p>Join It, Inc. will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
    <h3>Disclosure Of Data</h3>
    <h4>Disclosure for Law Enforcement</h4>
    <p>Under certain circumstances, Join It, Inc. may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
    <h4>Legal Requirements</h4>
    <p>Join It, Inc. may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
    <ul>
      <li>To comply with a legal obligation</li>
      <li>To protect and defend the rights or property of Join It, Inc.</li>
      <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
      <li>To protect the personal safety of users of the Service or the public</li>
      <li>To protect against legal liability</li>
    </ul>
    <h4>Security Of Data</h4>
    <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
    <h4>International Data Transfers Privacy Shield And Contractual Terms</h4>
    <p>Join It complies with the US-EU Privacy Shield Framework and Swiss-US Privacy Shield Framework (<a href="https://www.privacyshield.gov" target="_blank">https://www.privacyshield.gov</a>) as set forth by the US Department of Commerce regarding the collection, use, and retention of personal information from Individual Customers in the European Union member countries and Switzerland. Join It has certified that it adheres to the Privacy Shield Privacy Principles of notice, choice, accountability for onward transfer, security, data integrity and purpose limitation, access, recourse, enforcement and liability. If there is any conflict between the policies in this privacy policy and the Privacy Shield Privacy Principles, the Privacy Shield Privacy Principles shall govern. To learn more about the Privacy Shield program, and to view our certification page, please visit <a href="https://www.privacyshield.gov" target="_blank">https://www.privacyshield.gov</a></p>
    <p>In compliance with the US-EU and Swiss-US Privacy Shield Principles, Join It commits to resolve complaints about your privacy and our collection or use of your personal information. EU and Swiss individuals with questions or concerns about the use of their Personal Data should contact us at: <a href="mailto:support@joinit.org">support@joinit.org</a></p>
    <p>If you do not receive timely acknowledgement of your complaint, or if your complaint is not satisfactorily addressed by Join It, EU and Swiss individuals may bring a complaint before the <a href="http://ec.europa.eu/justice/data-protection/article-29/structure/data-protection-authorities/index_en.htm" target="_blank">EU Data Protection Authorities (DPAs)</a> and <a href="https://www.edoeb.admin.ch/edoeb/en/home/the-fdpic/task.html" target="_blank">Swiss Federal Data Protection and Information Commissioner (FDPIC)</a>. Finally, as a last resort and in limited situations, EU and Swiss individuals may seek redress from the Privacy Shield Panel, a binding arbitration mechanism.</p>
    <p>We also commit to cooperate with competent EU data protection authorities (DPAs) with regard to our customers end users’ human resources data transferred from a European country participating in the Privacy Shield in the context of the employment relationship.</p>
    <p>For additional details on Join It’s compliance with the EU-U.S. Privacy Shield Framework and the Swiss-U.S. Privacy Shield Frameworks, see <a href="/privacy-shield">Privacy Shield Notice</a></p>
    <h4>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h4>
    <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Join It, Inc. aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
    <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
    <p>In certain circumstances, you have the following data protection rights:</p>
    <p>The right to access, update or to delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>
    <p>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
    <p>The right to object. You have the right to object to our processing of your Personal Data.</p>
    <p>The right of restriction. You have the right to request that we restrict the processing of your personal information.</p>
    <p>The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>
    <p>The right to withdraw consent. You also have the right to withdraw your consent at any time where Join It, Inc. relied on your consent to process your personal information.</p>
    <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
    <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
    <h4>Service Providers</h4>
    <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
    <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
    <h3>Analytics</h3>
    <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
    <h4>Google Analytics</h4>
    <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
    <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>
    <p>For more information on the privacy practices of Google, please visit the Google Privacy and Terms web page: <a href="http://www.google.com/intl/en/policies/privacy" target="_blank">http://www.google.com/intl/en/policies/privacy/</a></p>
    <h4>Payments</h4>
    <p>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
    <p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
    <p>The payment processor we work with are:</p>
    <h5>Stripe</h5>
    <p>Their Privacy Policy can be viewed at <a href="https://stripe.com/us/privacy" target="_blank">https://stripe.com/us/privacy</a></p>
    <h4>Links To Other Sites</h4>
    <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
    <h4>Children's Privacy</h4>
    <p>Our Service does not address anyone under the age of 18 ("Children").</p>
    <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
    <h4>Changes To This Privacy Policy</h4>
    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
    <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
    <h4>Contacting Join It About Matters Related to Privacy</h4>
    <p>To contact Join It with requests, questions, or complaints on matters related to Privacy, please email <a href="mailto:support@joinit.org">support@joinit.org</a> and include “ATTN: Privacy Matter” in the subject line.</p>
  </div>  
</template>

<script>
export default {
  name: "PrivacyPolicyText",
  components:{
  },
}
</script>

<style lang="less" scoped>

</style>
